language: java
jdk:
- oraclejdk8
script:
- mvn verify
after_success:
- mvn coveralls:report
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy
  --settings travis/settings.xml
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - "/^bullet-core-[0-9]+\\.[0-9]+\\.[0-9]+/"
env:
  global:
    secure: EQlLQFHfpAFiiR2o0+Un8Lhesw3w/f/WR3stXsGN2VuEmpw1hYDzjD9FvtzqW8FqalD9AAwhCbn7G9DLQGyYoJOYnNGlQMAvUiKvxBkHuHlwNajGxO8Hq0bPljNjBM6anVXzmco77YLK0ylxRFdzfVwe645t/adis2vYosTGPCPqT/IN0EqL6hgWPQtAsdemLfJq68ZwFE3vdcaqp9BwaSP+J/i/tk2jECvwfvwJ4CELPkRZs2zyKvAGiqVvsUsz1x3aBK+cVkoQ+U6m1MRobYnHLkun4jmHkL5vBJbfRZsAGTH68rVg8HrjaxDXiLUWXqslePf5N4cGrdzA4zwFbcD3LC1Q6stkAKxKwKJRW/iFXzCFDdVTo7t2dHUVTu06IikNfmefaPSaAUQLWmv0lbqnfd02SM3yvINp9Yq428ezZZ7pEA/PzLl8kI8dfLHC+UnTRkmbhgPEGDQXJdDkjGC+VCymZqv6Cj1+cq5L1AhGzlfRpL7odB5mN5eUFg6/3jB1M4yz0o358DTQXS/2/Ls07hd6TFeZza2R/aF5kLiJQtBpDzXFNo2WZbX8a7bqgM8RF6i9O+bILHgmdVa4PegbD+81klE6594BX0K6ER7nthdlCRB1STSzxRyV0DSTbIM4ch3SdhQK0W17hTd/K0gAx5U/JkqDuQlfr1p2YxI=
dd:
  secure: LzEg8fu0uv2WsTWXzxR9McNlPdLoHh9Od+Is454Wh7bJ7//4Kwyev6/xCC/giVzms+/WIhXwQqroZwwHQP73LCa8N5MxcdTVWNz50zv0NIudvjaT5GC5EyUjRm1I99uZoa0GXfpkEDYDaikMwziqb4Y51spdcFx14D6HUaPGAsDxZnFefH+WHzC/TxJE3K6lVxsPS2JfV/T88kjxgHGuG/Wp54fuOT6/nZy7wX6Xn0cKK/T3PWUHUiwamdgGvM8vz4WGaVBwcxvsHi/9SKjVeBj2ZC/8UgGaaOTBxUK3Kdi9mbf/WYqvlKp8SZD8qK/qORU/4ifQQOkhxv5umqANynPquD9JmiQksGxNEbvVnWpoiRMj5QngJVkAY1thhNoVl7Quf7+EPx86E8QQ6HUKaYnNkJ6zeKX7ZnrqjCkvjLnAlnREDAuS4eDiY623aJYLkgTswoKptewRJEL9Gdi5o6F18zooWA4mDkwQn2rSjYiDtlFb4Wsn3ODqUJH5uG01cTb8dmAAg8Qsf7Hpy2YTYfbJaJpSrWWb9n7sqXwtNIsQzDzQvRJUG3OuVyXAmTCnJdH50ZAqLmy/KrBhUVyvcG2etzoh5XRwY4hM2bYf2o7HEfsOS2754ZRGXBf9JS/PtR0sbEShetXxwTIobWmJQuJjAcjUAEAO5m4wHCGG5oA=
